name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@master
    - name: Testing secret
      env: # Or as an environment variable
        GITHUB_TOKEN: ${{ secrets.TEST_INSTALL_CODE }}
      with: 
        args: comment "Here's my key."
      